name: SQL Code Deployment
 
on:
  push:
    branches:
      - dev  # Triggers the workflow on push to the main branch
    paths:
      - 'db/**'  # Trigger only when SQL files change
  pull_request:
    branches: 
      - dev
    paths:
      - 'db/**'
  workflow_dispatch:  # Allow manual trigger
  
 
jobs:
  deploy-sql:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Check out your repository
 
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the version of Python to install
 
    - name: Install SQL CLI
      run: |
        pip install sqlcmd  # Or any other CLI tool you are using for SQL execution
 
    - name: Deploy SQL scripts
      env:
        AZURE_SQL_SERVER: demo-sql-srvr-01.database.windows.net
        AZURE_SQL_DATABASE: demosqldb01
        AZURE_SQL_USERNAME: ${{ secrets.AZURE_SQL_USERNAME }}
        AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
      run: |
        # Example SQLCMD to execute SQL scripts
        sqlcmd -S $AZURE_SQL_SERVER -d $AZURE_SQL_DATABASE -U $AZURE_SQL_USERNAME -P $AZURE_SQL_PASSWORD -i ./db/sampledata.sql
 
    - name: Post-deployment Verification (Optional)
      run: |
        # Add any post-deployment steps like validation queries or tests
        echo "Post-deployment checks successful"
